<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-HOGD6GNA" failures="1" tests="3" name="ErrorTest" time="27.209" errors="0" timestamp="2024-03-06T20:56:15 CST">
  <testcase classname="Tutorial.Framework.ShopmodifiedErrorvalidationsTest" name="ErrorLogin" time="0.683"/>
  <testcase classname="Tutorial.Framework.ShopmodifiedErrorvalidationsTest" name="PlaceOrderError" time="3.721">
    <skipped/>
  </testcase> <!-- PlaceOrderError -->
  <testcase classname="Tutorial.Framework.ShopmodifiedErrorvalidationsTest" name="PlaceOrderError" time="8.149">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Tutorial.Framework.ShopmodifiedErrorvalidationsTest.PlaceOrderError(ShopmodifiedErrorvalidationsTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- PlaceOrderError -->
</testsuite> <!-- ErrorTest -->
