<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="6" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-04T15:18:36 CST" name="Suite" finished-at="2024-03-04T15:19:10 CST" duration-ms="33510">
    <groups>
      <group name="ErrorValidations">
        <method signature="ShopmodifiedErrorvalidationsTest.ErrorLogin()[pri:0, instance:Tutorial.Framework.ShopmodifiedErrorvalidationsTest@6be968ce]" name="ErrorLogin" class="Tutorial.Framework.ShopmodifiedErrorvalidationsTest"/>
      </group> <!-- ErrorValidations -->
    </groups>
    <test started-at="2024-03-04T15:18:36 CST" name="PassTest" finished-at="2024-03-04T15:19:02 CST" duration-ms="26251">
      <class name="Tutorial.Framework.ShopmodifiedwithJsonTest">
        <test-method is-config="true" signature="Launchapp()[pri:0, instance:Tutorial.Framework.ShopmodifiedwithJsonTest@210ab13f]" started-at="2024-03-04T15:18:37 CST" name="Launchapp" finished-at="2024-03-04T15:18:44 CST" duration-ms="7099" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launchapp -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Tutorial.Framework.ShopmodifiedwithJsonTest@210ab13f]" started-at="2024-03-04T15:18:44 CST" name="submitOrder" data-provider="getData" finished-at="2024-03-04T15:18:49 CST" duration-ms="5705" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Cream90!, email=strawberry@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="Launchapp()[pri:0, instance:Tutorial.Framework.ShopmodifiedwithJsonTest@210ab13f]" started-at="2024-03-04T15:18:49 CST" name="Launchapp" finished-at="2024-03-04T15:18:56 CST" duration-ms="7009" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launchapp -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Tutorial.Framework.ShopmodifiedwithJsonTest@210ab13f]" started-at="2024-03-04T15:18:56 CST" name="submitOrder" data-provider="getData" finished-at="2024-03-04T15:19:02 CST" duration-ms="6022" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Iamking@000, email=shetty@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
      </class> <!-- Tutorial.Framework.ShopmodifiedwithJsonTest -->
    </test> <!-- PassTest -->
    <test started-at="2024-03-04T15:18:36 CST" name="ErrorTest" finished-at="2024-03-04T15:19:10 CST" duration-ms="33510">
      <class name="Tutorial.Framework.ShopmodifiedErrorvalidationsTest">
        <test-method is-config="true" signature="Launchapp()[pri:0, instance:Tutorial.Framework.ShopmodifiedErrorvalidationsTest@6be968ce]" started-at="2024-03-04T15:18:36 CST" name="Launchapp" finished-at="2024-03-04T15:18:43 CST" duration-ms="7149" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launchapp -->
        <test-method signature="ErrorLogin()[pri:0, instance:Tutorial.Framework.ShopmodifiedErrorvalidationsTest@6be968ce]" started-at="2024-03-04T15:18:43 CST" name="ErrorLogin" finished-at="2024-03-04T15:18:45 CST" duration-ms="1654" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorLogin -->
        <test-method is-config="true" signature="Launchapp()[pri:0, instance:Tutorial.Framework.ShopmodifiedErrorvalidationsTest@6be968ce]" started-at="2024-03-04T15:18:45 CST" name="Launchapp" finished-at="2024-03-04T15:18:49 CST" duration-ms="3854" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launchapp -->
        <test-method retried="true" signature="PlaceOrderError()[pri:0, instance:Tutorial.Framework.ShopmodifiedErrorvalidationsTest@6be968ce]" started-at="2024-03-04T15:18:49 CST" name="PlaceOrderError" finished-at="2024-03-04T15:18:56 CST" duration-ms="6825" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at Tutorial.Framework.ShopmodifiedErrorvalidationsTest.PlaceOrderError(ShopmodifiedErrorvalidationsTest.java:46)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PlaceOrderError -->
        <test-method is-config="true" signature="Launchapp()[pri:0, instance:Tutorial.Framework.ShopmodifiedErrorvalidationsTest@6be968ce]" started-at="2024-03-04T15:18:56 CST" name="Launchapp" finished-at="2024-03-04T15:19:00 CST" duration-ms="4781" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launchapp -->
        <test-method signature="PlaceOrderError()[pri:0, instance:Tutorial.Framework.ShopmodifiedErrorvalidationsTest@6be968ce]" started-at="2024-03-04T15:19:00 CST" name="PlaceOrderError" finished-at="2024-03-04T15:19:09 CST" duration-ms="8810" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at Tutorial.Framework.ShopmodifiedErrorvalidationsTest.PlaceOrderError(ShopmodifiedErrorvalidationsTest.java:46)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PlaceOrderError -->
      </class> <!-- Tutorial.Framework.ShopmodifiedErrorvalidationsTest -->
    </test> <!-- ErrorTest -->
  </suite> <!-- Suite -->
</testng-results>
